use std::fmt::Write;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::Result;
use walkdir::WalkDir;

use super::types::Pkgbuild;

pub fn generate_pkginfo(pkgbuild: &Pkgbuild, pkgdir: &Path, arch: &str) -> Result<String> {
    let mut content = String::new();

    // Header
    writeln!(content, "# Generated by arch build")?;

    // Required fields
    writeln!(content, "pkgname = {}", pkgbuild.package_name())?;
    writeln!(content, "pkgbase = {}", pkgbuild.pkgbase)?;
    writeln!(content, "pkgver = {}", pkgbuild.full_version())?;

    // Optional string fields
    if let Some(desc) = &pkgbuild.pkgdesc {
        writeln!(content, "pkgdesc = {}", desc)?;
    }
    if let Some(url) = &pkgbuild.url {
        writeln!(content, "url = {}", url)?;
    }

    // Build metadata
    let builddate = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    writeln!(content, "builddate = {}", builddate)?;

    // Calculate installed size
    let size = calculate_dir_size(pkgdir)?;
    writeln!(content, "size = {}", size)?;

    writeln!(content, "arch = {}", arch)?;

    // Array fields
    for license in &pkgbuild.license {
        writeln!(content, "license = {}", license)?;
    }
    for dep in &pkgbuild.depends {
        writeln!(content, "depend = {}", dep)?;
    }
    for dep in &pkgbuild.optdepends {
        writeln!(content, "optdepend = {}", dep)?;
    }
    for dep in &pkgbuild.makedepends {
        writeln!(content, "makedepend = {}", dep)?;
    }
    for dep in &pkgbuild.checkdepends {
        writeln!(content, "checkdepend = {}", dep)?;
    }
    for provide in &pkgbuild.provides {
        writeln!(content, "provides = {}", provide)?;
    }
    for conflict in &pkgbuild.conflicts {
        writeln!(content, "conflict = {}", conflict)?;
    }
    for replace in &pkgbuild.replaces {
        writeln!(content, "replaces = {}", replace)?;
    }
    for backup in &pkgbuild.backup {
        writeln!(content, "backup = {}", backup)?;
    }

    Ok(content)
}

fn calculate_dir_size(dir: &Path) -> Result<u64> {
    let mut total = 0u64;

    for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            if let Ok(metadata) = entry.metadata() {
                total += metadata.len();
            }
        }
    }

    Ok(total)
}

pub fn write_pkginfo(pkgbuild: &Pkgbuild, pkgdir: &Path, arch: &str) -> Result<()> {
    let content = generate_pkginfo(pkgbuild, pkgdir, arch)?;
    std::fs::write(pkgdir.join(".PKGINFO"), content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_pkginfo() {
        let mut pkg = Pkgbuild::default();
        pkg.pkgbase = "test".to_string();
        pkg.pkgname = vec!["test".to_string()];
        pkg.pkgver = "1.0".to_string();
        pkg.pkgrel = "1".to_string();
        pkg.pkgdesc = Some("Test package".to_string());
        pkg.depends = vec!["glibc".to_string()];

        let tmpdir = std::env::temp_dir().join("pkginfo-test");
        std::fs::create_dir_all(&tmpdir).unwrap();

        let content = generate_pkginfo(&pkg, &tmpdir, "x86_64").unwrap();

        assert!(content.contains("pkgname = test"));
        assert!(content.contains("pkgver = 1.0-1"));
        assert!(content.contains("pkgdesc = Test package"));
        assert!(content.contains("depend = glibc"));
        assert!(content.contains("arch = x86_64"));

        std::fs::remove_dir_all(&tmpdir).ok();
    }
}
