//! .PKGINFO generation from environment variables

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use walkdir::WalkDir;

/// Calculate the total installed size of all files in a directory (excluding metadata files)
pub fn calculate_installed_size(pkgdir: &Path) -> Result<u64> {
    let mut total: u64 = 0;

    for entry in WalkDir::new(pkgdir).min_depth(1) {
        let entry = entry.context("Failed to read directory entry")?;
        let path = entry.path();

        // Skip metadata files
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            if name.starts_with('.') {
                continue;
            }
        }

        let meta = fs::symlink_metadata(path)?;
        if meta.is_file() {
            total += meta.len();
        }
    }

    Ok(total)
}

fn get_required_env(name: &str) -> Result<String> {
    env::var(name).with_context(|| format!("{} not set", name))
}

fn get_optional_env(name: &str) -> Option<String> {
    env::var(name).ok().filter(|value| !value.is_empty())
}

const ARRAY_SEPARATOR: char = '\u{1f}';

fn get_array_env(name: &str) -> Vec<String> {
    env::var(format!("ARCH_PKG_ARRAY_{}", name))
        .ok()
        .map(|value| {
            value
                .split(ARRAY_SEPARATOR)
                .filter(|item| !item.is_empty())
                .map(|item| item.to_string())
                .collect()
        })
        .unwrap_or_default()
}

pub fn package_arch() -> String {
    let architectures = get_array_env("arch");
    if architectures.iter().any(|arch| arch == "any") {
        return "any".to_string();
    }

    let host_arch = env::consts::ARCH;
    architectures
        .iter()
        .find(|arch| arch.as_str() == host_arch)
        .cloned()
        .or_else(|| architectures.into_iter().next())
        .unwrap_or_else(|| host_arch.to_string())
}

fn append_optional_field(
    content: &mut String,
    field_name: &str,
    field_value: Option<String>,
) -> Result<()> {
    if let Some(value) = field_value {
        writeln!(content, "{} = {}", field_name, value)?;
    }
    Ok(())
}

fn append_array_field(content: &mut String, field_name: &str, values: Vec<String>) -> Result<()> {
    for value in values {
        writeln!(content, "{} = {}", field_name, value)?;
    }
    Ok(())
}

fn append_pkg_version(
    content: &mut String,
    pkgver: &str,
    pkgrel: &str,
    epoch: Option<String>,
) -> Result<()> {
    if let Some(epoch_value) = epoch {
        writeln!(content, "pkgver = {}:{}-{}", epoch_value, pkgver, pkgrel)?;
    } else {
        writeln!(content, "pkgver = {}-{}", pkgver, pkgrel)?;
    }
    Ok(())
}

fn append_build_metadata(content: &mut String, size: u64, arch: Option<String>) -> Result<()> {
    let builddate = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    writeln!(content, "builddate = {}", builddate)?;
    writeln!(content, "size = {}", size)?;

    let arch_value = arch.unwrap_or_else(|| env::consts::ARCH.to_string());
    writeln!(content, "arch = {}", arch_value)?;
    Ok(())
}

fn append_dependency_fields(content: &mut String) -> Result<()> {
    append_array_field(content, "license", get_array_env("license"))?;
    append_array_field(content, "depend", get_array_env("depends"))?;
    append_array_field(content, "optdepend", get_array_env("optdepends"))?;
    append_array_field(content, "makedepend", get_array_env("makedepends"))?;
    append_array_field(content, "checkdepend", get_array_env("checkdepends"))?;
    append_array_field(content, "provides", get_array_env("provides"))?;
    append_array_field(content, "conflict", get_array_env("conflicts"))?;
    append_array_field(content, "replaces", get_array_env("replaces"))?;
    append_array_field(content, "backup", get_array_env("backup"))?;
    Ok(())
}

/// Generate .PKGINFO content from environment variables
pub fn generate_pkginfo(size: u64) -> Result<String> {
    let mut content = String::new();

    writeln!(content, "# Generated by arch-makepkg")?;

    let pkgname = get_required_env("pkgname")?;
    let pkgbase = get_optional_env("pkgbase").unwrap_or_else(|| pkgname.clone());
    let pkgver = get_required_env("pkgver")?;
    let pkgrel = get_required_env("pkgrel")?;

    writeln!(content, "pkgname = {}", pkgname)?;
    writeln!(content, "pkgbase = {}", pkgbase)?;
    append_pkg_version(&mut content, &pkgver, &pkgrel, get_optional_env("epoch"))?;
    append_optional_field(&mut content, "pkgdesc", get_optional_env("pkgdesc"))?;
    append_optional_field(&mut content, "url", get_optional_env("url"))?;
    append_build_metadata(&mut content, size, Some(package_arch()))?;
    append_dependency_fields(&mut content)?;

    Ok(content)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_calculate_installed_size() {
        let dir = TempDir::new().unwrap();
        let pkgdir = dir.path();

        // Create test files
        fs::create_dir_all(pkgdir.join("usr/bin")).unwrap();
        fs::write(pkgdir.join("usr/bin/hello"), "hello world").unwrap(); // 11 bytes
        fs::write(pkgdir.join("usr/bin/test"), "test").unwrap(); // 4 bytes

        // Metadata files should be excluded
        fs::write(pkgdir.join(".PKGINFO"), "pkgname = test").unwrap();

        let size = calculate_installed_size(pkgdir).unwrap();
        assert_eq!(size, 15); // 11 + 4
    }

    #[test]
    fn test_calculate_installed_size_empty() {
        let dir = TempDir::new().unwrap();
        let size = calculate_installed_size(dir.path()).unwrap();
        assert_eq!(size, 0);
    }

    #[test]
    fn test_generate_pkginfo() {
        // Set required env vars
        env::set_var("pkgname", "test-pkg");
        env::set_var("pkgver", "1.0.0");
        env::set_var("pkgrel", "1");
        env::set_var("pkgdesc", "A test package");
        env::set_var("ARCH_PKG_ARRAY_arch", "x86_64");
        env::set_var("ARCH_PKG_ARRAY_depends", "glibc\u{1f}openssl");
        env::set_var("ARCH_PKG_ARRAY_license", "MIT");

        let content = generate_pkginfo(12345).unwrap();

        assert!(content.contains("pkgname = test-pkg"));
        assert!(content.contains("pkgver = 1.0.0-1"));
        assert!(content.contains("pkgdesc = A test package"));
        assert!(content.contains("arch = x86_64"));
        assert!(content.contains("size = 12345"));
        assert!(content.contains("depend = glibc"));
        assert!(content.contains("depend = openssl"));
        assert!(content.contains("license = MIT"));

        // Clean up
        env::remove_var("pkgname");
        env::remove_var("pkgver");
        env::remove_var("pkgrel");
        env::remove_var("pkgdesc");
        env::remove_var("ARCH_PKG_ARRAY_arch");
        env::remove_var("ARCH_PKG_ARRAY_depends");
        env::remove_var("ARCH_PKG_ARRAY_license");
    }
}
