//! .PKGINFO generation from environment variables

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use walkdir::WalkDir;

/// Calculate the total installed size of all files in a directory (excluding metadata files)
pub fn calculate_installed_size(pkgdir: &Path) -> Result<u64> {
    let mut total: u64 = 0;

    for entry in WalkDir::new(pkgdir).min_depth(1) {
        let entry = entry.context("Failed to read directory entry")?;
        let path = entry.path();

        // Skip metadata files
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            if name.starts_with('.') {
                continue;
            }
        }

        let meta = fs::symlink_metadata(path)?;
        if meta.is_file() {
            total += meta.len();
        }
    }

    Ok(total)
}

/// Generate .PKGINFO content from environment variables
pub fn generate_pkginfo(size: u64) -> Result<String> {
    let mut content = String::new();

    // Helper to get required env var
    let get_required = |name: &str| -> Result<String> {
        env::var(name).with_context(|| format!("{} not set", name))
    };

    // Helper to get optional env var
    let get_optional =
        |name: &str| -> Option<String> { env::var(name).ok().filter(|s| !s.is_empty()) };

    // Helper to get array env var (space or newline separated)
    let get_array = |name: &str| -> Vec<String> {
        env::var(name)
            .ok()
            .map(|s| s.split_whitespace().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    };

    // Header
    writeln!(content, "# Generated by arch-makepkg")?;

    // Required fields
    let pkgname = get_required("pkgname")?;
    let pkgbase = get_optional("pkgbase").unwrap_or_else(|| pkgname.clone());
    let pkgver = get_required("pkgver")?;
    let pkgrel = get_required("pkgrel")?;

    writeln!(content, "pkgname = {}", pkgname)?;
    writeln!(content, "pkgbase = {}", pkgbase)?;

    // Version with optional epoch
    if let Some(epoch) = get_optional("epoch") {
        writeln!(content, "pkgver = {}:{}-{}", epoch, pkgver, pkgrel)?;
    } else {
        writeln!(content, "pkgver = {}-{}", pkgver, pkgrel)?;
    }

    // Optional string fields
    if let Some(desc) = get_optional("pkgdesc") {
        writeln!(content, "pkgdesc = {}", desc)?;
    }
    if let Some(url) = get_optional("url") {
        writeln!(content, "url = {}", url)?;
    }

    // Build metadata
    let builddate = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    writeln!(content, "builddate = {}", builddate)?;

    // Size
    writeln!(content, "size = {}", size)?;

    // Architecture
    let arch = get_optional("arch").unwrap_or_else(|| env::consts::ARCH.to_string());
    writeln!(content, "arch = {}", arch)?;

    // Array fields
    for license in get_array("license") {
        writeln!(content, "license = {}", license)?;
    }
    for dep in get_array("depends") {
        writeln!(content, "depend = {}", dep)?;
    }
    for dep in get_array("optdepends") {
        writeln!(content, "optdepend = {}", dep)?;
    }
    for dep in get_array("makedepends") {
        writeln!(content, "makedepend = {}", dep)?;
    }
    for dep in get_array("checkdepends") {
        writeln!(content, "checkdepend = {}", dep)?;
    }
    for provide in get_array("provides") {
        writeln!(content, "provides = {}", provide)?;
    }
    for conflict in get_array("conflicts") {
        writeln!(content, "conflict = {}", conflict)?;
    }
    for replace in get_array("replaces") {
        writeln!(content, "replaces = {}", replace)?;
    }
    for backup in get_array("backup") {
        writeln!(content, "backup = {}", backup)?;
    }

    Ok(content)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_calculate_installed_size() {
        let dir = TempDir::new().unwrap();
        let pkgdir = dir.path();

        // Create test files
        fs::create_dir_all(pkgdir.join("usr/bin")).unwrap();
        fs::write(pkgdir.join("usr/bin/hello"), "hello world").unwrap(); // 11 bytes
        fs::write(pkgdir.join("usr/bin/test"), "test").unwrap(); // 4 bytes

        // Metadata files should be excluded
        fs::write(pkgdir.join(".PKGINFO"), "pkgname = test").unwrap();

        let size = calculate_installed_size(pkgdir).unwrap();
        assert_eq!(size, 15); // 11 + 4
    }

    #[test]
    fn test_calculate_installed_size_empty() {
        let dir = TempDir::new().unwrap();
        let size = calculate_installed_size(dir.path()).unwrap();
        assert_eq!(size, 0);
    }

    #[test]
    fn test_generate_pkginfo() {
        // Set required env vars
        env::set_var("pkgname", "test-pkg");
        env::set_var("pkgver", "1.0.0");
        env::set_var("pkgrel", "1");
        env::set_var("pkgdesc", "A test package");
        env::set_var("arch", "x86_64");
        env::set_var("depends", "glibc openssl");
        env::set_var("license", "MIT");

        let content = generate_pkginfo(12345).unwrap();

        assert!(content.contains("pkgname = test-pkg"));
        assert!(content.contains("pkgver = 1.0.0-1"));
        assert!(content.contains("pkgdesc = A test package"));
        assert!(content.contains("arch = x86_64"));
        assert!(content.contains("size = 12345"));
        assert!(content.contains("depend = glibc"));
        assert!(content.contains("depend = openssl"));
        assert!(content.contains("license = MIT"));

        // Clean up
        env::remove_var("pkgname");
        env::remove_var("pkgver");
        env::remove_var("pkgrel");
        env::remove_var("pkgdesc");
        env::remove_var("arch");
        env::remove_var("depends");
        env::remove_var("license");
    }
}
